#!/usr/bin/env bash
install_cmd() {
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    nvm install v18.14.0
    nvm use v18.14.0
    npm install
}

build_cmd() {
    npm run compile
}

test_cmd() {
    export LOG_FILE=log_file.txt
    export LOG_LEVEL=0
    export GITHUB_TOKEN=none
    python3 run_test.py
}

run_cmd() {
    node build/src/index.js "$1"
}
case "$1" in
    install)
        install_cmd && exit 0

        echo "install command failed!"
        ;;
    build)
        build_cmd && exit 0

        echo "build command failed!"
        ;;
    test)
        test_cmd && exit 0

        echo "test command failed!"
        ;;
    *)
        if test -f "$1"; then
            run_cmd && exit 0

            echo "using url file failed!"
        else
            if test -d "$1"; then
                echo "$1 is a directory, not a file!"
            else
                echo "$1 does not exist!"
            fi
        fi
        ;;
esac

# if error: exit with code 1
exit 1

