version: '3'
services:
  express-api:
    build:
      context: ../
      dockerfile: ./docker/API/Dockerfile
    container_name: express-api
    depends_on:
      - sql-database
    volumes:
      - ../src:/usr/src/app/src
    ports:
      - 3000:3000
    networks:
      - API-Net
      - SQL-Net
  sql-database:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: 'secret_password'
    volumes:
      - postgres_volume1:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - SQL-Net
  adminer:
    image: adminer:latest
    container_name: adminer_container
    depends_on:
      - sql-database
    environment:
      ADMINER_DEFAULT_SERVER: sql-database
    ports:
      - 8080:8080
    links:
      - sql-database
    networks:
      - SQL-Net

volumes:
  postgres_volume1:
networks:
  SQL-Net:
  API-Net:
